language: python
python:
  - "3.4"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq mysql-server mysql-client
install: 
- "pip install -r src/current_cost/requirements.txt"
- "pip install -r src/rfxcom_toolbox/requirements.txt"
script: nosetests
